# -*- coding: utf-8 -*-
"""SED_comparison

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hF4kvFdABKjjVHhS-Grl3ZZ5PRYVRYRC
"""

import numpy as np
import matplotlib.pyplot as plt


# Paper SED
E_paper = np.array([791.4349854830851, 2039.4640401181593, 5311.942133618432,
                    13496.275849349473, 35202.84634456935, 93289.69467108532,
                    233787.43478336037])

Y_paper = np.array([3.4081900589907448e-06, 2.796725081358537e-06, 4.1058293138206534e-06,
                    6.403937784975619e-06, 1.2468536975082016e-05, 1.2671825152520149e-05,
                    1.141103568034108e-05])

E_left = np.array([495.5399275483192, 1281.7652483980671, 3289.3734936205633,
                   8596.317019351392, 22424.25519140909, 57226.87884808557,
                   149712.7423014118])

E_right = np.array([1274.0221530315162, 3303.005527845531, 8581.44774720149,
                    22073.324063998163, 57563.61144731918, 149468.15531392468,
                    392685.8588539841])

xerr_paper = np.vstack([E_paper - E_left, E_right - E_paper])

Y_bottom = np.array([1.7221830958905867e-06, 1.3995135637707941e-06, 2.616368793158353e-06,
                     4.6150245899628884e-06, 9.242143162469939e-06, 7.297567575936536e-06,
                     2.9534124573781334e-06])

Y_top = np.array([np.nan, np.nan, 5.571563850240318e-06, 8.293846741176347e-06,
                  1.5713069415563257e-05, 1.7938176072256042e-05, 1.971444973869249e-05])

yerr_paper_lower = Y_paper - Y_bottom
yerr_paper_upper = Y_top - Y_paper


# Redone analysis SED

e_min = np.array([501.18723362727246, 1000.0, 3162.2776601683795, 10000.0,
                  31622.776601683792, 100000.0, 199526.2314968879])

e_ref = np.array([707.945784384138, 1778.2794100389228, 5623.413251903491,
                  17782.794100389227, 56234.13251903491, 141253.75446227554,
                  281838.2931264449])

e_max = np.array([1000.0, 3162.2776601683795, 10000.0, 31622.776601683792,
                  100000.0, 199526.2314968879, 398107.1705534973])

xerr_redone = np.vstack([e_ref - e_min, e_max - e_ref])

y_redone = np.array([2.0724184859165183e-06, 3.920824827946227e-06, 6.574915160903724e-06,
                     1.004936222549198e-05, 1.639581765031345e-05, 1.5790224094419538e-05,
                     1.5177434468731354e-05])

yerr_redone = np.array([1.6864809719285255e-06, 1.3860018777700394e-06, 1.540139104119794e-06,
                        2.1322017444743665e-06, 3.7310916519789952e-06, 7.8525392917367e-06,
                        8.369857988404212e-06])

yul_redone = np.array([4.6068796465302875e-06, 6.7057687222656576e-06, 9.89732036347216e-06,
                       1.4754149259849399e-05, 2.4609106736145947e-05, 3.485046442457995e-05,
                       3.043958583480313e-05])

ts_redone = np.array([1.2060673251980916, 10.277621371205896, 27.016942317335634,
                      40.69579849645379, 47.38346033548805, 14.13223615314655,
                      5.436624557925825])

ts_thresh = 4.0
det_r = ts_redone >= ts_thresh
ul_r = ~det_r


# Standard analysis SED

e_min_std = np.array([
    501.18723362727246,
    1584.893192461114,
    5011.872336272725,
    15848.93192461114,
    50118.72336272725,
    158489.3192461114])

e_ref_std = np.array([
    891.2509381337459,
    2818.382931264455,
    8912.509381337459,
    28183.82931264455,
    89125.0938133746,
    251188.6431509582])

e_max_std = np.array([
    1584.893192461114,
    5011.872336272725,
    15848.93192461114,
    50118.72336272725,
    158489.3192461114,
    398107.1705534969])

xerr_std = np.vstack([
    e_ref_std - e_min_std,
    e_max_std - e_ref_std])

e2dnde_std = np.array([
    2.3045262504444393e-06,
    4.427313307381554e-06,
    8.393806256546588e-06,
    1.3917923184916173e-05,
    1.584233958866068e-05,
    1.783425455630097e-05])

e2dnde_errp_std = np.array([
    4.6774788065953535e-07,
    4.547281392673731e-07,
    5.731282488929509e-07,
    9.414184023539529e-07,
    1.6164512348581202e-06,
    3.0765167014047814e-06])

e2dnde_errn_std = np.array([
    4.661287255549589e-07,
    4.495068539329489e-07,
    5.660084832685629e-07,
    9.095932182825378e-07,
    1.5031180391933435e-06,
    2.727038399808238e-06])


# High energy analysis SED

e_min_he = np.array([
    3019.952,
    6309.573,
    12589.254,
    25118.864,
    50118.723,
    100000.000,
    199526.231,
    398107.171])

e_ref_he = np.array([
    4365.1583224,
    8912.50938134,
    17782.79410039,
    35481.33892336,
    70794.57843841,
    141253.75446228,
    281838.29312644,
    630957.34448019])

e_max_he = np.array([
    6309.573,
    12589.254,
    25118.864,
    50118.723,
    100000.000,
    199526.231,
    398107.171,
    1000000.000])

xerr_he = np.vstack([
    e_ref_he - e_min_he,
    e_max_he - e_ref_he])

e2dnde_he = np.array([
    5.57412584e-06,
    8.95846855e-06,
    1.01052685e-05,
    1.49230907e-05,
    1.50332998e-05,
    1.95157558e-05,
    1.96485684e-05,
    1.05198502e-05])

e2dnde_err_he = np.array([
    6.46488363e-07,
    6.99253153e-07,
    9.64224789e-07,
    1.70173284e-06,
    1.82198349e-06,
    2.98379682e-06,
    5.08921139e-06,
    4.11152069e-06])


fig, ax = plt.subplots(figsize=(9, 6))

lw = 2.0
ms = 8
mew = 1.8

# Redone analysis
ax.errorbar(
    e_ref[det_r], y_redone[det_r],
    xerr=xerr_redone[:, det_r],
    yerr=yerr_redone[det_r],
    fmt='o',
    linestyle='none',
    color='k', ecolor='k',
    elinewidth=lw, capsize=0,
    markersize=ms, markeredgewidth=mew,
    markerfacecolor='k',
    label='Redone analysis')


ax.errorbar(
    e_ref[ul_r], yul_redone[ul_r],
    xerr=xerr_redone[:, ul_r],
    yerr=yul_redone[ul_r] * 0.2,
    uplims=True,
    fmt='o',
    linestyle='none',
    color='k', ecolor='k',
    elinewidth=lw, capsize=0,
    markersize=ms, markeredgewidth=mew,
    markerfacecolor='white')

# Paper
ax.errorbar(
    E_paper[2:], Y_paper[2:],
    xerr=xerr_paper[:, 2:],
    yerr=[yerr_paper_lower[2:], yerr_paper_upper[2:]],
    fmt='s',
    linestyle='none',
    color='#00008B', ecolor='#00008B',
    elinewidth=lw, capsize=0,
    markersize=ms, markeredgewidth=mew,
    markerfacecolor='#00008B',
    label='Abdo et al.')


ax.errorbar(
    E_paper[:2], Y_paper[:2],
    xerr=xerr_paper[:, :2],
    yerr=Y_paper[:2] * 0.25,
    uplims=True,
    fmt='s',
    linestyle='none',
    color='#00008B', ecolor='#00008B',
    elinewidth=lw, capsize=0,
    markersize=ms, markeredgewidth=mew,
    markerfacecolor='white')

# Standard Analysis
ax.errorbar(
    e_ref_std,
    e2dnde_std,
    xerr=xerr_std,
    yerr=[e2dnde_errn_std, e2dnde_errp_std],
    fmt='o',
    linestyle='none',
    color='red',
    ecolor='red',
    elinewidth=2.5,
    capsize=3,
    markersize=8,
    markeredgewidth=1.8,
    markerfacecolor='white',
    label='Standard analysis',
    zorder=10)

# High energy analysis
ax.errorbar(
    e_ref_he,
    e2dnde_he,
    xerr=xerr_he,
    yerr=e2dnde_err_he,
    fmt='o',
    linestyle='none',
    color='green',
    ecolor='green',
    elinewidth=2.5,
    capsize=3,
    markersize=8,
    markeredgewidth=1.8,
    markerfacecolor='white',
    label='High energy analysis',
    zorder=11)

ax.set_xscale('log')
ax.set_yscale('log')
ax.set_xlabel('Energy (MeV)', fontsize=14)
ax.set_ylabel(r'$E^2 dN/dE$ (MeV cm$^{-2}$ s$^{-1}$)', fontsize=14)
ax.grid(False)
ax.legend(loc='upper left', frameon=True, fontsize=13)

plt.tight_layout()
plt.show()