# -*- coding: utf-8 -*-
"""var_test

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wc4tZnrU_wQUetPDQDagsCfmMIE9YvZZ
"""

import numpy as np
import scipy.stats as stats
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

time = np.array([1,2,3,4,5,6,7])

flux = np.array([
    2.679e-09, 2.736e-09, 2.874e-09,
    2.328e-09, 2.422e-09, 2.716e-09, 2.327e-09])

flux_err = np.array([
    1.42e-10, 1.6e-10, 1.09e-10,
    1.42e-10, 1.2e-10, 1.24e-10, 1.98e-10])


# Chi square

def chi_square_test(flux, flux_err, weighted=False):
    if weighted:
        mean_flux = np.average(flux, weights=1/(flux_err**2))
        label = "Weighted mean"
    else:
        mean_flux = np.mean(flux)
        label = "Unweighted mean"

    chi2 = np.sum(((flux - mean_flux) / flux_err) ** 2)
    dof = len(flux) - 1
    p_value = 1 - stats.chi2.cdf(chi2, dof)
    sigma = stats.norm.ppf(1 - p_value / 2)

    return chi2, dof, p_value, sigma, mean_flux, label



for weighted in [False, True]:
    chi2, dof, p, sigma, mean_flux, label = chi_square_test(flux, flux_err, weighted)
    print(f"{label}: χ²={chi2:.2f}, dof={dof}, p={p:.2e}, significance={sigma:.2f}σ")



# Anova test

def anova_test(time, flux, num_bins=3):
    bins = np.array_split(np.argsort(time), num_bins)
    groups = [flux[b] for b in bins]
    return stats.f_oneway(*groups)

f_stat, p_anova = anova_test(time, flux)
print(f"ANOVA: F={f_stat:.2f}, p={p_anova:.4f}")



# Excess variance

def excess_variance(flux, flux_err):
    var_obs = np.var(flux, ddof=1)
    mean_err2 = np.mean(flux_err**2)

    excess_var = max(var_obs - mean_err2, 0)
    delta_excess_var = np.sqrt(2 * np.mean(flux_err**4) / len(flux_err))

    rms = np.sqrt(excess_var)
    sigma = excess_var / delta_excess_var if delta_excess_var > 0 else 0

    return excess_var, rms, delta_excess_var, sigma