# -*- coding: utf-8 -*-
"""fluxvstimebins

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f-Wr98tbPfffL4bz3vDRw-ujO0aflz5V
"""

import numpy as np
import matplotlib.pyplot as plt

# Updated flux values
flux = np.array([
    2.679e-09,
    2.736e-09,
    2.874e-09,
    2.328e-09,
    2.422e-09,
    2.716e-09,
    2.327e-09
])

flux_err = np.array([
    1.42e-10,
    1.6e-10,
    1.09e-10,
    1.42e-10,
    1.2e-10,
    1.24e-10,
    1.98e-10
])



flux_full = 2.617e-09
flux_full_err = 4.67e-11

plt.figure(figsize=(7,5))


plt.errorbar(bins, flux, yerr=flux_err, fmt='o', capsize=3, linewidth=1)


plt.axhline(flux_full, linestyle='--', linewidth=1)

plt.fill_between([bins.min()-0.5, bins.max()+0.5],
                 flux_full - flux_full_err,
                 flux_full + flux_full_err,
                 alpha=0.1)

plt.xlim(bins.min()-0.5, bins.max()+0.5)
plt.xlabel("Time bin")
plt.ylabel(r"Flux (ph cm$^{-2}$ s$^{-1}$)")

plt.tight_layout()
plt.savefig("flux_vs_timebins_fixed.png")
plt.show()
